// <auto-generated />
namespace ElectionProgram.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class answertype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(answertype));
        
        string IMigrationMetadata.Id
        {
            get { return "201803202050436_answertype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
